### ISSUE TITLE
We have a clean install of easy-ssb-pub with no invites given out but in ssh we can see our pub connect to 2 other pubs

### ISSUE THREAD

**Issue by fredhampton** [staltz/easy-ssb-pub#15]
We have a clean install of easy-ssb-pub with no invites given out but in ssh we can see our pub connect to 2 other pubs

Connected ssb.joelmello.com:8008:@nRk7cZFeBoCARklvbrOMvUjZ5MZ0NC429k+gccGGHOE=.ed25519
Connected pub.37i.net:8008:@ZZSaYcKvwzqlIw43LyfJhGMu7HzXtsX3s4emi/GP0ew=.ed25519

Have these 2 pub been added to scale the service ?
Is there a way to not have these pubs connect to our pub ?

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. Yes, this project was built to have pubs discover each other via DHT, check https://github.com/staltz/easy-ssb-pub/blob/9842272f1ecbb4a9276c732b5f9ddf61c6b30b99/src/index.ts#L6

I understand this may not be desirable. In the near future I want to provide three modes for this pub server project, and you would be able to choose when spawning the server: http://viewer.scuttlebot.io/%75TLIcLvePsXjgy+ZFrkmVg/0RIwQSJqCl8Cc6Q6Uso=.sha256

For now, I recommend either (1) forking this project, (2) running vanilla sbot, (3) waiting for the change.

**Comment by fredhampton** [comment]
Thanks so much for your answer !!!
Can we comment out the below to prevent the discovery via DHT ?
createDiscoveryPeer(ssbBot, ssbConf);

**Comment by staltz** [comment]
Yes, it should be enough.
