### ISSUE TITLE
Update or version-lock TypeScript

### ISSUE THREAD

**Issue by pztrn** [staltz/easy-ssb-pub#18]
Debian 9, node 6.9.1, installed using latest method from README and latest sources from Github. Output:

```
> easy-ssb-pub@4.0.0 start /home/ssb/easy-ssb-pub
> tsc && node dist/index --host $HOST --no-discovery

src/discovery.ts(113,3): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<Response>'.
  Type '{}' is not assignable to type 'Response'.
    Property 'text' is missing in type '{}'.
```

**Comment by staltz** [comment]
TypeScript's fault for issuing a breaking change as a minor version bump. I'll fix it, but just to make it clear: TypeScript's fault.

**Comment by pztrn** [comment]
Well, managed to get it working by using commands from Dockerfile, so it look like README needs to be updated.

**Comment by gmarcos87** [comment]
Is there any workaround? I have the same problem.

**Comment by taniki** [comment]
@gmarcos87 edit the `package.json` and replace the needed typescript version

```
-    "typescript": "^2.3.2"
+    "typescript": "2.3.2"
```
