### ISSUE TITLE
Add option to restrict memory consumption

### ISSUE THREAD

**Issue by don-smith** [staltz/easy-ssb-pub#4]
Currently there is a [memory leak in Scuttlebot](/ssbc/scuttlebot/issues/194) which causes me to have to restart my pub at least once every couple of days (sometimes twice a day). I'm running my pub on a DigitalOcean dropplet with 1GB of RAM. If we add [memory constraints](https://docs.docker.com/engine/reference/run/#/user-memory-constraints) and a [restart policy](https://docs.docker.com/engine/reference/run/#/restart-policies---restart) we won't have to monitor the pub and start it after it falls over. It will just restart when memory consumption is too high.

I'm happy to test this and submit a PR.

**Comment by staltz** [comment]
Yes that would be great.

**Comment by staltz** [comment]
I did this in the README.md
