### ISSUE TITLE
We have a clean install of easy-ssb-pub with no invites given out but see pub connections ?

### ISSUE THREAD

**Issue by fredhampton** [staltz/easy-ssb-pub#7]
We have a clean install of easy-ssb-pub with no invites given out but in ssh we can see our pub see 
 Connected ssb.joelmello.com:8008:@nRk7cZFeBoCARklvbrOMvUjZ5MZ0NC429k+gccGGHOE=.ed25519
Connected pub.37i.net:8008:@ZZSaYcKvwzqlIw43LyfJhGMu7HzXtsX3s4emi/GP0ew=.ed25519

Have these 2 pub been added to scale the service ?

**Comment by staltz** [comment]
May I ask how you solved it? :)

**Comment by fredhampton** [comment]
Why were these 2 pubs added ?
How do we know that they are not malicious ?
If they were added for scale can this be mentioned Read Me ?

Thanks

**Comment by fredhampton** [comment]
We have a clean install of easy-ssb-pub with no invites given out but in ssh we can see our pub see
Connected ssb.joelmello.com:8008:@nRk7cZFeBoCARklvbrOMvUjZ5MZ0NC429k+gccGGHOE=.ed25519
Connected pub.37i.net:8008:@ZZSaYcKvwzqlIw43LyfJhGMu7HzXtsX3s4emi/GP0ew=.ed25519

Have these 2 pub been added to scale the service ?

Why were these 2 pubs added ?
How do we know that they are not malicious ?
If they were added for scale can this be mentioned Read Me ?

Thanks
