### ISSUE TITLE
easy-ssb-pub fails to install

### ISSUE THREAD

**Issue by radiospiel** [staltz/easy-ssb-pub#8]
I just powered up a digital ocean docker instance, based on ubuntu 16.04, and tried to install easy-ssb-pub, according to the instructions in README.md. Yet, this failed:

```
git clone https://github.com/staltz/easy-ssb-pub.git
cd easy-ssb-pub/
PUB_URL=xxx.yyy.org docker-compose up -d
[ ... ]
npm info attempt registry request try #1 at 12:17:18 PM
npm http fetch GET https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz
npm http fetch 200 https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz
npm info lifecycle easy-ssb-pub@2.0.0~preinstall: easy-ssb-pub@2.0.0

Killed
ERROR: Service 'easy_ssb_pub' failed to build: The command '/bin/sh -c . $HOME/.nvm/nvm.sh && npm install' returned a non-zero code: 137
```

A full log can be found here: https://gist.github.com/radiospiel/c2b2981badffff42671850617bbb3d8d

Note that quite some time went by between `npm info lifecycle easy-ssb-pub@2.0.0~preinstall: easy-ssb-pub@2.0.0`, and that I didn't kill anything manually.

**Comment by yangwao** [comment]
Have same issue.

**Comment by voodoohop** [comment]
me too

**Comment by ahdinosaur** [comment]
hey all, i wonder if the `npm install` is hitting the [memory limit of 450 MB](https://github.com/staltz/easy-ssb-pub/blob/master/docker-compose.yaml#L16). maybe try disabling that?

**Comment by yangwao** [comment]
@ahdinosaur yes, I think it helped, thanks for hint! Wasn't aware of that. 
@staltz you can close this if someone else can replicate it as fix.
Anyway, I'm considering make just image and remove nvm dependency.

**Comment by ahdinosaur** [comment]
@yangwao great. :+1: similar to %kTsKX06zp6dWMt/JMVmFQLLnzU9RSOmHV9n7+MQ7tdI=.sha256, if you have anything to share after your journey, please do!

**Comment by voodoohop** [comment]
fixed it for me! thanks

**Comment by radiospiel** [comment]
with a 1GB digital ocean instance I can confirm that the build seems to work fine, with these warnings that should be ok:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

However, after starting the container via

    root@ssbc:~/easy-ssb-pub# docker start easy-ssb-pub

I see the "Secure Scuttlebutt is a P2P network ideal for data, identity, and messaging" page. However, when I ask for an invite this fails with 

```
TypeError: Cannot read property 'match' of undefined
    at Object.isPrivate (/usr/src/app/node_modules/scuttlebot/node_modules/ip/lib/ip.js:262:14)
    at Object.<anonymous> (/usr/src/app/node_modules/scuttlebot/plugins/invite.js:71:40)
    at apply (/usr/src/app/node_modules/muxrpc-validation/index.js:173:15)
    at Object.<anonymous> (/usr/src/app/node_modules/muxrpc-validation/index.js:82:14)
    at Object.hooked (/usr/src/app/node_modules/hoox/index.js:10:15)
    at /usr/src/app/dist/http.js:23:20
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```

(in the browser)

**Comment by carloslfu** [comment]
Hi @radiospiel I had the same issue and I have find the solution. When you set "PUB_URL=publicurltoyourserv.er" in the installation you should put the domain name only, e.g. put "PUB_URL=myssb.com" instead of "PUB_URL=http://myssb.com", this has resolved the issue for me.

**Comment by staltz** [comment]
Hi :)
Thanks for letting us know. It appears people have found the solutions.

**Comment by adamyonk** [comment]
PSA: I had to give my Digital Ocean droplet 1 GB memory temporarily to give yarn enough space to install everything it needed.
